# Generated by Django 2.1.4 on 2018-12-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20181209_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Gymkhana_body',
            options={},
        ),
    ]
