# Generated by Django 2.1.4 on 2018-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20181209_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymkhana_body',
            name='nameofbody',
            field=models.CharField(default='Gymkhana', max_length=100),
        ),
        migrations.AddField(
            model_name='gymkhana_body',
            name='secretary_name',
            field=models.CharField(default='Secy', max_length=100),
        ),
    ]
