# Generated by Django 2.1.4 on 2018-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='totalvotes',
            field=models.IntegerField(default=0),
        ),
    ]
